title = "scon.stdout"
baseURL = "https://stephenchappo.github.io/"
languageCode = "en-us"
theme = "hugo-creative-theme"
disableKinds = ["taxonomy", "taxonomyTerm"]
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
	name = "Stephen Chapman"
	description = "Personal Blog"
	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "scon.stdout"

		[params.navigation.links]
			about     = "About"
			portfolio = "Posts"
			contact   = "Contact"

	# Hero section
	[params.hero]
		slogan     = "scon.stdout"
		subtitle   = "Garbage collection."
		buttonText = "More"

	# About section
	[params.about]
		headline    = "What is this?"
		description = "Somewhere for me to dump various things I'm up to and keep a running record."
		buttonText  = "Get started!"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

	# Contact section
	[params.contact]
		headline = "Contact Me"
		description = "Got something on your mind?"
		email = "scon.and.on.and.on@gmail.com"
